### ISSUE TITLE
Merge peti's nix script

### ISSUE THREAD

**Issue by bgamari** [hvr/head.hackage#13]
@peti has written a nice little script for using head.hackage patches within nix. It seems like it would be much more discoverable if it was in mainline.

**Comment by peti** [comment]
I'll create a PR to add https://github.com/peti/head.hackage/blob/master/scripts/generate-nix-overrides.hs into this repo tomorrow. Generally speaking, my ideas was to use this script to provide all these patches as part of Nixpkgs automaticallly, i.e. users of `haskell.packages.ghcHEAD` would get all those patches transparently.

**Comment by mpickering** [comment]
I have modified the original script quite a bit in order to make the process more automated. I'll try to clean it up and make a PR today.

**Comment by peti** [comment]
I suppose this issue can be closed.

**Comment by bgamari** [comment]
Peter Simons <notifications@github.com> writes:

> I suppose this issue can be closed.
>
Yes, I suppose so. Thanks @peti!

**Comment by mpickering** [comment]
More documentation: http://mpickering.github.io/posts/2018-01-05-ghchead-nix.html
