### ISSUE TITLE
Include link to this repository from head.hackage.haskell.org/

### ISSUE THREAD

**Issue by bgamari** [hvr/head.hackage#38]
https://head.hackage.haskell.org/ should at very least contain a link to this repository so users will know where to start if they want to use this infrastructure.

**Comment by hvr** [comment]
It always contained a link to this repository... don't be fooled by the jedi mind trick... :)

**Comment by phadej** [comment]
`head.hackage` upstream repository will be moving to GitLab  https://gitlab.haskell.org/ghc/head.hackage

Announced at https://mail.haskell.org/pipermail/ghc-devs/2019-July/017934.html

---

I'm closing this issue here, please reopen it on GitLab if it's still relevant.
