### ISSUE TITLE
Include directions on how to use new-update with head.hackage

### ISSUE THREAD

**Issue by RyanGlScott** [hvr/head.hackage#45]
After upgrading to `cabal-install-2.2`, the `head.hackage.sh` script was kind enough to tell me:

```
INFO: 'cabal' is recent enough and supports 'cabal new-update head.hackage'; you can try using that directly!
```

I decided to follow its advice, but I quickly stumbled:

```
$ cabal new-update head.hackage
cabal: 'new-update' repo(s): "head.hackage" can not be found in known remote
repo(s): hackage.haskell.org
```

There appears to be at least one extra step I need to perform to make this work, but what that is isn't clear to me. It would be helpful to have these extra steps documented in the `README` for future reference.

**Comment by hvr** [comment]
...it should have picked up the remote-repo decl in your `cabal.project(.local)`

**Comment by RyanGlScott** [comment]
Huh? My usual workflow (before `cabal-install-2.2`) was:

```
$ ./head.hackage.sh update
$ ./head.hackage.sh init
```

I need to run `update` beforehand to ensure that the `cabal.project` file generated by `init` is up to date. That is to say, I'm doing this _before_ `init`ting, so no `cabal.project` file will even be present at that point.

**Comment by hvr** [comment]
Oh right; `head.hackage.sh update` does some magic here... it generates a temporary cabal.project file, which contains the repo statement;

But I don't understand why you need to run `update` before `init`; I don't think there's anything in `init` that relies on `update` having been run beforehand.

**Comment by RyanGlScott** [comment]
I see—I think I was under the misconception that the contents of `init` were influenced by the state of `head.hackage` at a given moment. But in that case, why does `head.hackage.sh` always work, but `cabal new-update` doesn't work unless specific files are present?

**Comment by RyanGlScott** [comment]
(I'll close this since my original request was invalid, but I am still curious to know the answer to my question in https://github.com/hvr/head.hackage/issues/45#issuecomment-377221145.)

**Comment by hvr** [comment]
> But in that case, why does head.hackage.sh always work, but cabal new-update doesn't work unless specific files are present?

Not sure if I understand your question right but `cabal new-update` needs to know about the head.hackage repo (including the sign-keys) from somewhere; either from the global config (currently not recommended), or from a `cabal.project` file that's in scope somewhere. `head.hackage.sh update` temporarily provides such a configuration which is why it "always works".

**Comment by RyanGlScott** [comment]
That makes sense, thanks.
