### ISSUE TITLE
Describe the stack workflow in README / document if no such workflow is possible.

### ISSUE THREAD

**Issue by alexanderkjeldaas** [hvr/head.hackage#46]
Is there a workflow for using the pre-built cross-comipiler binaries with stack, and the overlay?

**Comment by hvr** [comment]
I'd expect there to be but I just don't know. If somebody could figure out how to subdue Stack into using `head.hackage` we can add it to the README.

**Comment by phadej** [comment]
`head.hackage` upstream repository will be moving to GitLab  https://gitlab.haskell.org/ghc/head.hackage

Announced at https://mail.haskell.org/pipermail/ghc-devs/2019-July/017934.html

---

I'm closing this issue here, please reopen it on GitLab if it's still relevant.
