### ISSUE TITLE
head.hackage's use of --pristine occasionally causes problems

### ISSUE THREAD

**Issue by RyanGlScott** [hvr/head.hackage#65]
Currently, trying to build any package that depends on `vector-algorithms-0.7.0.1` (such as `criterion`) breaks when using `head.hackage`. This appears to be the culprit:

1. There currently exists a [`head.hackage` patch for `vector-algorithms-0.7.0.1`](https://github.com/hvr/head.hackage/blob/481f9a034f8cb1a8ad3d36b6a3a77409791463e4/patches/vector-algorithms-0.7.0.1.patch), which is applied against the pristine (i.e., revision-less) package.
2. Separately, there exists a [Hackage revision for `vector-algorithms-0.7.0.1`](http://hackage.haskell.org/package/vector-algorithms-0.7.0.1/revisions/), which permits it to build against the newest version of `vector`, 0.12.0.1. (Crucially, this is the only version of `vector` that appears to build with GHC 8.6.1-alpha1.)

It appears that the Hackage revision is not being applied, however, since `cabal-install` tries to pick an install plan using `vector-0.11.0.0`, not `vector-0.12.0.1`. If you try to override this:

```
$ cabal new-configure --enable-tests --enable-benchmarks --allow-newer=base,unix,template-haskell,Cabal,ghc,stm,containers,unix --constraint=vector==0.12.0.1
'cabal.project.local' file already exists. Now overwriting it.
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: lens-4.16.1 (user goal)
[__1] rejecting: lens:!bench (constraint from config file, command line flag,
or user target requires opposite flag selection)
[__1] trying: lens:*bench
[__2] trying: criterion-1.4.1.0 (dependency of lens *bench)
[__3] trying: vector-algorithms-0.7.0.1 (dependency of criterion)
[__4] next goal: vector (dependency of lens)
[__4] rejecting: vector-0.12.0.1 (conflict: vector-algorithms => vector>=0.6
&& <0.12)
[__4] rejecting: vector-0.12.0.0, vector-0.11.0.0, vector-0.10.12.3,
vector-0.10.12.2, vector-0.10.12.1, vector-0.10.11.0, vector-0.10.10.0,
vector-0.10.9.2, vector-0.10.9.1, vector-0.10.9.0, vector-0.10.0.1,
vector-0.10, vector-0.9.1, vector-0.9, vector-0.8, vector-0.7.1,
vector-0.7.0.1, vector-0.7, vector-0.6.0.2, vector-0.6.0.1, vector-0.6,
vector-0.5, vector-0.4.2, vector-0.4.1, vector-0.4, vector-0.3.1, vector-0.3,
vector-0.2, vector-0.1, vector-0.10.12.0, vector-0.10.9.3 (constraint from
command line flag requires ==0.12.0.1)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: vector, vector-algorithms, lens,
criterion, lens:bench, base
```

`cabal-install` appears to think that `vector-algorithms-0.7.0.1`'s upper version bounds on `vector` are `<0.12`, which is further evidence that the Hackage revision is not being applied.

**Comment by bgamari** [comment]
N.B. the use of `cabal unpack --pristine` was introduced in 203ca69a78fc0196f2390804c3e3655d423449ac.

**Comment by RyanGlScott** [comment]
I suppose a suitable workaround for the time being would be to include all of the changes that have been made to `vector-algorithms-0.7.0.1` via revisions within its `head.hackage` patch. It's ugly, but I can't think of a better way at the moment.

**Comment by RyanGlScott** [comment]
Thoughts on this, @angerman? I find myself having to go through great effort to work around this issue on a regular basis, so it would be good to figure out a better solution.

**Comment by RyanGlScott** [comment]
Sure, I'd be fine with automating the process of porting over revisions. As it stands, 90% of the `.cabal` files that I check in to `head.hackage` are exact copies of the latest revisions on Hackage, which feels unnecessary.

**Comment by phadej** [comment]
Why copies need to be checked in. Couldn't they be simply removed, head.hackage is an overlay after all?

**Comment by hvr** [comment]
After discussing this with Ryan a bit more, I think we found way to mitigate the pain: have the scripting automatically pick up upstream Hackage revisions if there's no explicit `.cabal` file checked into head.hackage nor any modification by the `.patch` file to the .cabal file.

**Comment by phadej** [comment]
`head.hackage` upstream repository will be moving to GitLab  https://gitlab.haskell.org/ghc/head.hackage

Announced at https://mail.haskell.org/pipermail/ghc-devs/2019-July/017934.html

---

I'm closing this issue here, please reopen it on GitLab if it's still relevant.
