### ISSUE TITLE
proteaaudio build exposes `overlay.nix`'s maloverride of `gnutls`

### ISSUE THREAD

**Issue by deepfire** [hvr/head.hackage#96]
When building `proteaaudio` with `overrides.nix`, an anomalous patch override of `gnutls` (the non-Haskell package) pops up.  What's used as a patch is equally curious -- the generated `patches.nix` file itself.

The dependency chain for `proteaaudio` is `libpulseaudio` -> `dbus` -> `systemd` -> `libmicrohttpd` -> `gnutls`.

**Comment by phadej** [comment]
`head.hackage` upstream repository will be moving to GitLab  https://gitlab.haskell.org/ghc/head.hackage

Announced at https://mail.haskell.org/pipermail/ghc-devs/2019-July/017934.html

---

I'm closing this issue here, please reopen it on GitLab if it's still relevant.
