### ISSUE TITLE
Moving the GHC 8.8 story forward

### ISSUE THREAD

**Issue by deepfire** [hvr/head.hackage#98]
I made some overrides that allowed me to build a fairly large application on GHC 8.8 using the [`nix-head`](https://github.com/deepfire/nix-head) workbench.  (Note, that `nix-head` directly uses `head.hackage` (using `overrides.nix`), and adds a way to specify _extra overrides_ conveniently. You can see the details on the project page.)

While this result is not _immediately_ useful for `head.hackage`, I think it might still have some worth as a reference.

1. Commit pins: https://github.com/deepfire/nix-head/tree/master/pins
2. Nix overrides: https://github.com/deepfire/nix-head/blob/master/extra-overrides.nix

Notes (will update as I remember):
1. The `jailbreaks` are indications that `.cabal` updates are necessary.
2. The `dontHaddock`s are because of `haddock` segfaulting on many of the packages.
3. The `headCabal` and `headPatch` disables indicate that the `head.hackage`'s changes had to be undone.

**Comment by phadej** [comment]
`head.hackage` upstream repository will be moving to GitLab  https://gitlab.haskell.org/ghc/head.hackage

Announced at https://mail.haskell.org/pipermail/ghc-devs/2019-July/017934.html

---

I'm closing this issue here, please reopen it on GitLab if it's still relevant.
